baseURL="https://tunafei.me/"
languageCode="zh-cn"
title="春天的小池塘"
ignoreFiles=["^content/private/"]
theme="PaperMod"

# SEO基础（方便被搜索引擎收录）
enableRobotsTXT=true
[sitemap]
  changefreq="weekly"
  priority=0.5
  filename="sitemap.xml"

[params]
  author = "Jeff"
